### ISSUE TITLE
Why is this library preferable? 

### ISSUE THREAD

**Issue by mrmayfield** [seegno/bitcoin-core#11]
Just saw node-bitcoin points towards this repo:

`If starting a new project, I highly encourage you to take a look at the more modern bitcoin-core.`

Wondering why using this library is preferable? Thanks!

**Comment by mrmayfield** [comment]
Right off the bat, it seems like the library supports lots of ES6 out of the box, is that kind of the main pitch?

**Comment by freewil** [comment]
Yes, ES6 also with optional promise support.

**Comment by freewil** [comment]
Also, it adds support for the new REST API, in addition to the RPC methods.

**Comment by mrmayfield** [comment]
Okay cool, just reading up on the REST API now.

Correct me if I'm wrong, but: https://bitcoin.org/en/developer-reference#http-rest it looks like the REST API is unauthenticated and can only be run from localhost?

Also, we should probably get a url to the API documentation for the RPC calls somewhere in the readme, since it's not there at all and I'm wondering which Bitcoin docs are most up to date.

**Comment by ruimarinho** [comment]
Like @freewil mentioned, the main differences are:

- Modern codebase using ES2015.
- Dual API (choose between callbacks or Promises by passing a function as the last argument or not, based on your coding preference).
- Consistent domain error in case you need to wrap your try/catch statements.
- REST interface support.
- Docker support (not really a feature but it spawned two different bitcoind Docker repositories).

Regarding the REST api, it defaults to localhost and is unauthenticated. I'm unsure if binding can be changed.

The methods are linked right under [the methods header](https://github.com/seegno/bitcoin-core#methods). Probably a bit obscure but I'm open to a PR if you'd like to propose something else.

**Comment by mrmayfield** [comment]
Yes, I found those methods but they don't have any information on how the API is used (ie which parameters to pass etc). We probably want to link to the actual API information as well.

**Comment by ruimarinho** [comment]
@mrmayfield does #12 address your suggestion?

**Comment by mrmayfield** [comment]
Definitely looks a lot better. I know there's a lot of RPC calls that are mentioned here though. Maybe we want to link to the 'definitive up to date API' documentation if such a thing exists ?

**Comment by ruimarinho** [comment]
Unfortunately, I don't think such documentation exists and linking to the source code might not be helpful for many users.
