### ISSUE TITLE
Support Bitcoin's maximum precision

### ISSUE THREAD

**Issue by pedrobranco** [seegno/bitcoin-core#16]
When parsing a Bitcoin/Crypto response that has an value with more than 15 significant digits: example is `1222223333.00000001`.

The lib **request** with option 

``` javascript
{ json:true }
```

 used by `bitcoin-core` uses `JSON.parse` which loses precision returning the amount `1222223333`.

Suggestion: use **request** with 

``` javascript
{ json: false }
```

and parse the raw output with the lib [json-bigint-string](https://www.npmjs.com/package/json-bigint-string).

@ruimarinho @nunofgs @fixe

**Comment by ruimarinho** [comment]
Closed by https://github.com/seegno/bitcoin-core/pull/17.
