### ISSUE TITLE
Please add Typescript Type Definition supports.

### ISSUE THREAD

**Issue by UnsignedInt8** [seegno/bitcoin-core#25]
Hello, could you please add typescript type definition file for 'bitcoin-core' ? 

Typescript type definition can help developers get the powerful IntelliSense in Visual Studio/Vscode. So, I hope you could write this file. Thank you.

You may reference these articles to write a typescript type definition file:

[https://blog.mariusschulz.com/2014/05/19/using-typescripts-type-definition-files-to-get-tooling-support-for-plain-javascript](https://blog.mariusschulz.com/2014/05/19/using-typescripts-type-definition-files-to-get-tooling-support-for-plain-javascript
)

[https://typescript.codeplex.com/wikipage?title=Writing%20Definition%20%28.d.ts%29%20Files](https://typescript.codeplex.com/wikipage?title=Writing%20Definition%20%28.d.ts%29%20Files)

**Comment by ruimarinho** [comment]
Would you be interested in submitting a PR for this?

**Comment by ruimarinho** [comment]
@UnsignedInt8 closing this issue but feel free to submit a PR if you think it'd be beneficial for the community.
