### ISSUE TITLE
Queuing mechanism for RPC calls

### ISSUE THREAD

**Issue by johnbailon** [seegno/bitcoin-core#26]
Is a queuing mechanism for RPC calls in the pipeline? I've been hitting timeouts even with an increased `rpcworkqueue` setting on `bitcoin.conf` and I figured the best solution is to implement a queue.

**Comment by ruimarinho** [comment]
Not on the short term @johnbailon, but I'd be open to a PR for that. We could look into how [ioredis](https://github.com/luin/ioredis) does it.
